# Generated by Django 2.2.5 on 2020-10-10 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='heroinfo',
            table='tb_heros',
        ),
    ]
